security:
    encoders:
        App\Entity\Employee:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Employee
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LogAuthAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: main

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
#    access_control:
#        - { path: '/employee', roles: ROLE_ADMIN }
#        - { path: '^/animal/diary/note', roles: ROLE_ETHOLOGUE }

    role_hierarchy:
        ROLE_ADMIN: ROLE_ETHOLOGUE
        ROLE_ETHOLOGUE: ROLE_USER
